name: flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  gal: ^2.3.0
  shared_preferences: ^2.5.5
  http: ^1.2.1
  camera: ^0.11.0

  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2

  # ML Packages
  google_mlkit_face_detection: ^0.13.2
  tflite_flutter: ^0.12.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/poses/1_person.png
    - assets/poses/2_person.png
    - assets/poses/3_person.png
    - assets/poses/4_person.png
    - assets/images/
